Create evaluation readme
covid19-forecast-hub-europe/covid19-forecast-hub-europe pull request #3142
Opened 2023-07-17 12:11 UTC by kathsherratt

This PR visualises ensemble performance in:
- a README, modified from ensemble evaluation presentation (code by @sbfnk plus a couple of figure captions)
- run via github action workflow, each Tuesday and Wednesday (similar to the timing of the website model reports)

2023-07-17 15:14 UTC, sbfnk requested changes
Thanks, looks great! A few quick suggestions:
- put it in `evaluation/` rather than `code/evaluation` - my bad for pointing to the wrong place, sorry! I've added the text from the existing README there
- maybe edit action here instead of adding a new one? Makes no difference in practice but might be preferable to have less code https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/0d3e120f4af6a01a7b221a6746ac6b2d75f65380/.github/workflows/scoring.yml#L33
- can you also render once and commit just so we can check what the plots look ilke?

2023-07-17 15:14 UTC, sbfnk commented on code/evaluation/README.Rmd
> +## Number of models in ensemble
```suggestion
# Data files of forecast scores

The files `scores.csv` contains "raw" scores for each data/forecast point based on the predictive quantiles and where the data ended up relative to them. For each combination of date, target variable and location we report the [Weighted Interval Score](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008618) (`wis`) as well as its components of `sharpness`, `underprediction` and `overprediction`, the absolute error of the median (`aem`), [Bias](https://doi.org/10.1371/journal.pcbi.1006785) (`bias`), coverage at the 50 and 95% levels (`cov_50`/`cov_95`), and the number of quantiles supplied (`n_quantiles`).

The `weekly-summary` folder contains weekly evaluations that enter the [weekly performance reports](https://covid19forecasthub.eu/reports.html).

# Ensemble performance
## Number of models in ensemble
```

2023-07-17 15:14 UTC, sbfnk commented on .github/workflows/render-readme-evaluation.yml
> +        run: Rscript -e 'rmarkdown::render("code/evaluation/README.Rmd")'
```suggestion
        run: Rscript -e 'rmarkdown::render("evaluation/README.Rmd")'
```

2023-07-17 15:14 UTC, sbfnk commented on .github/workflows/render-readme-evaluation.yml
> +          git commit README.md -m 'Re-build evaluation README.Rmd' || echo "No changes to commit"
Does this have to be:

```suggestion
          git commit evaluation/README.md -m 'Re-build evaluation README.Rmd' || echo "No changes to commit"
```

2023-07-17 15:14 UTC, sbfnk commented on .github/workflows/render-readme-evaluation.yml
> +      - code/evaluation/README.Rmd
```suggestion
      - evaluation/README.Rmd
```

2023-07-17 20:57 UTC, kathsherratt commented
Thanks! Implemented those suggestions. Please merge if you think it's ready (of course no problem to edit).

2023-07-18 09:05 UTC, sbfnk approved these changes

2023-07-18 09:05 UTC, merged